//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WY_47_89.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WY_47_89.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] cli {
            get {
                object obj = ResourceManager.GetObject("cli", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Core {
            get {
                object obj = ResourceManager.GetObject("Confuser_Core", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Confuser_DynCipher {
            get {
                object obj = ResourceManager.GetObject("Confuser_DynCipher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Protections {
            get {
                object obj = ResourceManager.GetObject("Confuser_Protections", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Renamer {
            get {
                object obj = ResourceManager.GetObject("Confuser_Renamer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Confuser_Runtime {
            get {
                object obj = ResourceManager.GetObject("Confuser_Runtime", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;project outputDir=&quot;%out%&quot; baseDir=&quot;%base%&quot; debug=&quot;true&quot; xmlns=&quot;http://confuser.codeplex.com&quot;&gt;
        ///  &lt;rule pattern=&quot;true&quot; preset=&quot;maximum&quot; inherit=&quot;false&quot;&gt;
        ///    &lt;protection id=&quot;anti ildasm&quot; /&gt;
        ///    &lt;protection id=&quot;anti tamper&quot; /&gt;
        ///    &lt;protection id=&quot;constants&quot; /&gt;
        ///    &lt;protection id=&quot;ctrl flow&quot; /&gt;
        ///    &lt;protection id=&quot;anti dump&quot; /&gt;
        ///    &lt;protection id=&quot;anti debug&quot; /&gt;
        ///    &lt;protection id=&quot;invalid metadata&quot; /&gt;
        ///    &lt;protection id=&quot;ref proxy&quot; /&gt;
        ///    &lt;protection id=&quot;resources&quot; /&gt;
        ///    &lt;protection id=&quot;rename&quot; /&gt;
        ///  &lt;/rule&gt;
        ///  [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string def {
            get {
                return ResourceManager.GetString("def", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Play
        ///Ever
        ///Got
        ///For.
        /// </summary>
        internal static string Dictionary {
            get {
                return ResourceManager.GetString("Dictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] dnlib {
            get {
                object obj = ResourceManager.GetObject("dnlib", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Management;
        ///using System.Collections.Generic;
        ///using Microsoft.Win32;
        ///using System.Security.Cryptography;
        ///using System.Reflection;
        ///
        ///
        ///[assembly: AssemblyTitle(&quot;%$#@basictrigger0@#$%&quot;)]
        ///[assembly: AssemblyVersion(&quot;%$#@assemblytrigger0@#$%&quot;)]
        ///[assembly: AssemblyFileVersion(&quot;%$#@assemblytrigger1@#$%&quot;)]
        ///[assembly: AssemblyDescription(&quot;%$#@basictrigger1@#$%&quot;)]
        ///[assembly: AssemblyCompany(&quot;% [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ExpStub {
            get {
                return ResourceManager.GetString("ExpStub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap hudson {
            get {
                object obj = ResourceManager.GetObject("hudson", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Management;
        ///using System.Collections.Generic;
        ///using Microsoft.Win32;
        ///using System.Security.Cryptography;
        ///using System.Reflection;
        ///
        ///[assembly: AssemblyTitle(&quot;ConfuserEx GUI&quot;)]
        ///[assembly: AssemblyDescription(&quot;ConfuserEx&quot;)]
        ///[assembly: AssemblyCompany(&quot;Ki&quot;)]
        ///[assembly: AssemblyProduct(&quot;ConfuserEx&quot;)]
        ///[assembly: AssemblyVersion(&quot;1.0.0&quot;)]
        ///[assembly: AssemblyFileVersion(&quot;1.0.0&quot;)]
        ///
        ///
        ///#pragma [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string stub {
            get {
                return ResourceManager.GetString("stub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Management;
        ///using System.Collections.Generic;
        ///using Microsoft.Win32;
        ///using System.Security.Cryptography;
        ///using System.Reflection;
        ///
        ///
        ///#if %%%RandomAssembly%%%
        ///[assembly: AssemblyTitle(&quot;%$#@basictrigger0@#$%&quot;)]
        ///[assembly: AssemblyVersion(&quot;%$#@assemblytrigger0@#$%&quot;)]
        ///[assembly: AssemblyFileVersion(&quot;%$#@assemblytrigger1@#$%&quot;)]
        ///[assembly: AssemblyDescription(&quot;%$#@basictrigger1@#$%&quot;)]
        ///[ass [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string StubStarter {
            get {
                return ResourceManager.GetString("StubStarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Management;
        ///using System.Collections.Generic;
        ///using Microsoft.Win32;
        ///using System.Security.Cryptography;
        ///using System.Reflection;
        ///using System.Windows.Forms;
        ///
        ///
        ///[assembly: AssemblyTitle(&quot;%$#@basictrigger0@#$%&quot;)]
        ///[assembly: AssemblyVersion(&quot;%$#@assemblytrigger0@#$%&quot;)]
        ///[assembly: AssemblyFileVersion(&quot;%$#@assemblytrigger1@#$%&quot;)]
        ///[assembly: AssemblyDescription(&quot;%$#@basictrigger1@#$%&quot;)]
        ///[ [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SuperStub {
            get {
                return ResourceManager.GetString("SuperStub", resourceCulture);
            }
        }
    }
}
